[[main]]
none = "none"

[[main]]
name = "posts"
pageRef = "/posts"
identifier = "JBcHmVJs3R"
weight = 1

[[main]]
name = "projects"
pageRef = "/projects"
identifier = "ShEZEWlG3o"
weight = 2

[[main]]
name = "about"
pageRef = "/about"
identifier = "p3yhEKdfMn"
weight = 3

[[footer]]
none = "none"
