[[main]]
none = "none"

[[main]]
name = "posts"
pageRef = "/posts"
identifier = "JBcHmVJs3R"
weight = 9999

[[main]]
name = "projects"
pageRef = "/projects"
identifier = "ShEZEWlG3o"
weight = 9999

[[footer]]
none = "none"
